// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/types — DO NOT EDIT.
// Regenerate with: make types

//////////
// source: api.go
/*
Package types holds the request/response DTOs for the custom API routes.

These structs are the single source of truth for API payload shapes:
`make types` runs tygo, which converts every exported type in this
package to TypeScript in shared/types.gen.ts. Never hand-edit the
generated file — change the Go struct and regenerate.
*/

/**
 * HealthResponse is returned by GET /api/app/health.
 */
export interface HealthResponse {
  status: string;
  version: string;
}
/**
 * PostStats is returned by GET /api/app/posts/stats.
 */
export interface PostStats {
  total: number /* int64 */;
  published: number /* int64 */;
  drafts: number /* int64 */;
}
/**
 * PublishPostResponse is returned by POST /api/app/posts/{id}/publish.
 */
export interface PublishPostResponse {
  id: string;
  slug: string;
  published: boolean;
}
