package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

func applyExtra(cfg Config, extra Extra) error {
	switch extra {
	case ExtraEmailVerification:
		return writeEmailVerificationMigration(cfg)
	case ExtraShadcn:
		return nil // instructions only — see NextSteps
	default:
		return fmt.Errorf("unknown extra %q", extra)
	}
}

// --- Docker ------------------------------------------------------------

func writeDockerFiles(cfg Config) error {
	files := map[string]string{
		"Dockerfile":         backendDockerfile(cfg),
		".dockerignore":      dockerignore,
		"docker-compose.yml": composeFile(cfg),
	}

	if cfg.Frontend == FrontendNext {
		files["frontend/Dockerfile"] = nextDockerfile
	}

	for name, content := range files {
		path := filepath.Join(cfg.TargetDir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func backendDockerfile(cfg Config) string {
	if cfg.Frontend == FrontendInertia {
		// Monolith: build the frontend assets into the backend image.
		return `# --- frontend assets ---
FROM node:22-alpine AS assets
WORKDIR /src/frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
COPY shared/ ../shared/
RUN npm run build

# --- backend ---
FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app ./cmd/app

FROM alpine:3.21
WORKDIR /srv
COPY --from=build /app ./app
COPY --from=assets /src/frontend/dist ./frontend/dist
COPY frontend/root.html ./frontend/root.html
EXPOSE 8090
VOLUME /srv/pb_data
CMD ["./app", "serve", "--http=0.0.0.0:8090"]
`
	}

	return `FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app ./cmd/app

FROM alpine:3.21
WORKDIR /srv
COPY --from=build /app ./app
EXPOSE 8090
VOLUME /srv/pb_data
CMD ["./app", "serve", "--http=0.0.0.0:8090"]
`
}

const nextDockerfile = `FROM node:22-alpine AS build
WORKDIR /src/frontend
COPY package*.json ./
RUN npm ci
COPY . ./
COPY --from=shared . ../shared/
RUN npm run build

FROM node:22-alpine
WORKDIR /srv
ENV NODE_ENV=production
COPY --from=build /src/frontend/.next/ ./.next/
COPY --from=build /src/frontend/node_modules/ ./node_modules/
COPY --from=build /src/frontend/package.json ./
EXPOSE 3000
CMD ["npx", "next", "start"]
`

const dockerignore = `pb_data/
frontend/node_modules/
frontend/.next/
frontend/dist/
.git/
`

func composeFile(cfg Config) string {
	compose := `services:
  backend:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/srv/pb_data
`

	if cfg.Auth == AuthClerk {
		compose += `    environment:
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
`
	}

	if cfg.Frontend == FrontendNext {
		compose += `
  frontend:
    build:
      context: frontend
      additional_contexts:
        shared: shared
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_POCKETBASE_URL: http://backend:8090
`
		if cfg.Auth == AuthClerk {
			compose += `      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
`
		}
		compose += `    depends_on:
      - backend
`
	}

	compose += `
volumes:
  pb_data:
`
	return compose
}

// --- Email verification --------------------------------------------------

// writeEmailVerificationMigration adds a migration that requires a verified
// email to authenticate (PocketBase's AuthRule on the users collection).
func writeEmailVerificationMigration(cfg Config) error {
	name := fmt.Sprintf("%d_require_verified_email.go", time.Now().Unix())
	path := filepath.Join(cfg.TargetDir, "migrations", name)

	const content = `package migrations

import (
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
	"github.com/pocketbase/pocketbase/tools/types"
)

// Requires users to verify their email before they can authenticate.
// Generated by fullstack-template (extra: email-verification).
func init() {
	m.Register(func(app core.App) error {
		users, err := app.FindCollectionByNameOrId("users")
		if err != nil {
			return err
		}

		users.AuthRule = types.Pointer("verified = true")

		return app.Save(users)
	}, func(app core.App) error {
		users, err := app.FindCollectionByNameOrId("users")
		if err != nil {
			return err
		}

		users.AuthRule = types.Pointer("")

		return app.Save(users)
	})
}
`

	return os.WriteFile(path, []byte(content), 0o644)
}
